diff -ruN a/Makefile b/Makefile
--- a/Makefile	2014-12-03 10:13:32.486463458 +0300
+++ b/Makefile	2014-12-03 10:14:10.994462934 +0300
@@ -45,7 +45,7 @@
 DATESTR=$(shell /bin/echo -n "built on "; date)
 set_deb_version:
 	DEBEMAIL=$(DEBEMAIL) dch \
-		--newversion $(VERSION)-$(REVISION)$(BPTAG) \
+		--newversion $(VERSION)-$(REVISION)$(BPTAG) -u low \
 		-D $(DIST) --force-bad-version --force-distribution "$(DATESTR)"
 
 build:
